import os
import re
import SCons.Script  
from model import  *
from physical_platform import  *

# the purpose of this build stage is to provide the run script context
# about programming the FPGA.  We could have done this in LEAP configure
# but we have enough hooks to do it outside, so that we don't have to touch 

class FPGAProgram(ProjectDependency):
  def __init__(self, moduleList):
    fpgaFile = open('config/' + moduleList.apmName + '.fpga','w') 
    fpgaFile.write('#Generated by build pipeline\n')
    try:
      fpgaFile.write('FPGA=' + FPGA_PLATFORM + '\n')
    except:
      fpgaFile.write('FPGA=DEFAULT\n')
